apiVersion: v1
kind: ConfigMap
metadata:
  name: gestock-config
data:
  # Oracle Database Configuration
  DB_HOST: "oracle-db"
  DB_PORT: "1521"
  DB_USERNAME: "GESTOCK"
  DB_NAME: "FREEPDB1"

  # Backend Configuration
  PORT: "3000"

  # Frontend Configuration
  BACKENDBASEURL: "http://localhost:30300/api"
